services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=blocapp'
      - 'POSTGRES_PASSWORD=blocapp'
      - 'POSTGRES_USER=blocapp'
    ports:
      - '5551:5432'
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
