spring:
  datasource:
    url: jdbc:postgresql://localhost:5551/blocapp
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET:meu-secret-temporario}
  expiration-ms: 86400000